schema_version: 1

context:
  name: M2Crypto
  version: "0.47.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: 9256300be1e0412be802aa1f827e0ce7f94deb1099b8ccdcfd9867a7f0f975bf
  patches:
    - 0006-Disable-system-SDK-includes-on-macOS.patch
    - 0008-Use-Python-3-C-API-names-dropped-by-SWIG-4.3.patch
    - 0009-Define-the-PRAGMA-helpers-before-using-them.patch
    - 0010-Do-not-corrupt-test-cookies-into-control-characters.patch

build:
  number: 0
  skip: win
  script:
    - sed -i.bak -e "/sys\/types.h/d" -e "/stdint.h>/d" $PREFIX/include/openssl/e_os2.h
    - export LDFLAGS="-L$PREFIX/lib $LDFLAGS"
    - export CFLAGS="-I$PREFIX/include $CFLAGS"
    - export OPENSSL_PATH=$PREFIX
    - ${{ PYTHON }} -m pip install . -vv
    - mv $PREFIX/include/openssl/e_os2.h{.bak,}

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - swig
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - openssl
    - pip
    - python
    - setuptools >=75.8.1
    - swig >=2.0.4
    - wheel
  run:
    - openssl
    - packaging
    - python

tests:
  - python:
      imports:
        - M2Crypto
        - M2Crypto.SSL
  - files:
      source:
        - tests
    requirements:
      run:
        - parameterized
        - pip
        - pytest
    script:
      - pip check
      - python -m pytest tests/ -v -rs -k "not test_ssl"

about:
  license: BSD-2-Clause
  license_file: LICENSES/BSD-2-Clause.txt
  summary: "M2Crypto: A Python crypto and SSL toolkit"
  homepage: https://gitlab.com/m2crypto/m2crypto

extra:
  recipe-maintainers:
    - chrisburr
