schema_version: 1

context:
  name: M2Crypto
  version: "0.46.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: 5de32576c3bfc84fc2972ba703305dcba35dfb40383273e9552a7e17175dcb72
  patches:
    - 0004-Fix-double-free-from-bad-refactoring.patch
    - 0005-Fix-windows-by-dropping-OpenSSL-1.1-support.patch
    - 0006-Disable-system-SDK-includes-on-macOS.patch
    - 0007-fix-m2urllib-don-t-fail-with-missing-urllib.request..patch

build:
  number: 0
  skip: win
  script:
    - if: not win
      then:
        - sed -i.bak -e "/sys\/types.h/d" -e "/stdint.h>/d" $PREFIX/include/openssl/e_os2.h
        - export LDFLAGS="-L$PREFIX/lib $LDFLAGS"
        - export CFLAGS="-I$PREFIX/include $CFLAGS"
        - export OPENSSL_PATH=$PREFIX
        - ${{ PYTHON }} -m pip install . -vv
        - mv $PREFIX/include/openssl/e_os2.h{.bak,}
      else:
        - set "OPENSSL_PATH=%LIBRARY_PREFIX%"
        - ${{ PYTHON }} -m pip install . -vv
requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - swig
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - openssl
    # The workaround for the e_os2.h issue doesn't work on Windows
    - if: win
      then:
        - openssl <3.3
        - swig <4.3
    - pip
    - python
    - setuptools
    - swig >=2.0.4
  run:
    - openssl
    - python

tests:
  - python:
      imports:
        - M2Crypto
        - M2Crypto.SSL
  - files:
      source:
        - tests
    requirements:
      run:
        - parameterized
        - pip
        - pytest
    script:
      - pip check
      - python -m pytest tests/ -v -rs -k "not test_ssl"

about:
  license: MIT
  license_file: LICENCE
  summary: "M2Crypto: A Python crypto and SSL toolkit"
  homepage: https://gitlab.com/m2crypto/m2crypto

extra:
  recipe-maintainers:
    - chrisburr
